Transmorpher_Titles = {
{id=1, name="Private %s"},
{id=2, name="Corporal %s"},
{id=3, name="Sergeant %s"},
{id=4, name="Master Sergeant %s"},
{id=5, name="Sergeant Major %s"},
{id=6, name="Knight %s"},
{id=7, name="Knight-Lieutenant %s"},
{id=8, name="Knight-Captain %s"},
{id=9, name="Knight-Champion %s"},
{id=10, name="Lieutenant Commander %s"},
{id=11, name="Commander %s"},
{id=12, name="Marshal %s"},
{id=13, name="Field Marshal %s"},
{id=14, name="Grand Marshal %s"},
{id=15, name="Scout %s"},
{id=16, name="Grunt %s"},
{id=17, name="Sergeant %s"},
{id=18, name="Senior Sergeant %s"},
{id=19, name="First Sergeant %s"},
{id=20, name="Stone Guard %s"},
{id=21, name="Blood Guard %s"},
{id=22, name="Legionnaire %s"},
{id=23, name="Centurion %s"},
{id=24, name="Champion %s"},
{id=25, name="Lieutenant General %s"},
{id=26, name="General %s"},
{id=27, name="Warlord %s"},
{id=28, name="High Warlord %s"},
{id=29, name="Gladiator %s"},
{id=30, name="Duelist %s"},
{id=31, name="Rival %s"},
{id=32, name="Challenger %s"},
{id=33, name="Scarab Lord %s"},
{id=34, name="Conqueror %s"},
{id=35, name="Justicar %s"},
{id=36, name="Champion of the Naaru %s"},
{id=37, name="Merciless Gladiator %s"},
{id=38, name="%s of the Shattered Sun"},
{id=39, name="Hand of A'dal %s"},
{id=40, name="Vengeful Gladiator %s"},
{id=41, name="Battlemaster %s"},
{id=42, name="%s the Seeker"},
{id=43, name="Elder %s"},
{id=44, name="Flame Warden %s"},
{id=45, name="Flame Keeper %s"},
{id=46, name="%s the Exalted"},
{id=47, name="%s the Explorer"},
{id=48, name="%s the Diplomat"},
{id=49, name="Brutal Gladiator %s"},
{id=50, name="Arena Master %s"},
{id=51, name="Salty %s"},
{id=52, name="Chef %s"},
{id=53, name="%s the Supreme"},
{id=54, name="%s of the Ten Storms"},
{id=55, name="%s of the Emerald Dream"},
{id=56, name="Deadly Gladiator %s"},
{id=57, name="Prophet %s"},
{id=58, name="the Malefic %s"},
{id=59, name="Stalker %s"},
{id=60, name="%s of the Ebon Blade"},
{id=61, name="Archmage %s"},
{id=62, name="Warbringer %s"},
{id=63, name="Assassin %s"},
{id=64, name="Grand Master Alchemist %s"},
{id=65, name="Grand Master Blacksmith %s"},
{id=66, name="Iron Chef %s"},
{id=67, name="Grand Master Enchanter %s"},
{id=68, name="Grand Master Engineer %s"},
{id=69, name="Doctor %s"},
{id=70, name="Grand Master Angler %s"},
{id=71, name="Grand Master Herbalist %s"},
{id=72, name="Grand Master Scribe %s"},
{id=73, name="Grand Master Jewelcrafter %s"},
{id=74, name="Grand Master Leatherworker %s"},
{id=75, name="Grand Master Miner %s"},
{id=76, name="Grand Master Skinner %s"},
{id=77, name="Grand Master Tailor %s"},
{id=81, name="%s the Immortal"},
{id=82, name="%s the Undying"},
{id=83, name="%s Jenkins"},
{id=84, name="Bloodsail Admiral %s"},
{id=85, name="%s the Insane"},
{id=86, name="%s of the Exodar"},
{id=87, name="%s of Darnassus"},
{id=88, name="%s of Ironforge"},
{id=89, name="%s of Stormwind"},
{id=90, name="%s of Orgrimmar"},
{id=91, name="%s of Sen'jin"},
{id=92, name="%s of Silvermoon"},
{id=93, name="%s of Thunder Bluff"},
{id=94, name="%s of the Undercity"},
{id=95, name="%s the Noble"},
{id=96, name="Crusader %s"},
{id=97, name="%s of Gnomeregan"},
{id=98, name="%s of the Darkspear"},
{id=99, name="%s the Argent Champion"},
{id=100, name="%s, Guardian of Cenarius"},
{id=101, name="Brewmaster %s"},
{id=102, name="Merrymaker %s"},
{id=103, name="%s the Love Fool"},
{id=104, name="Matron %s"},
{id=105, name="Patron %s"},
{id=106, name="Obsidian Slayer %s"},
{id=107, name="Twilight Vanquisher %s"},
{id=108, name="%s, Conqueror of Naxxramas"},
{id=109, name="%s, Hero of the Frozen Wastes"},
{id=110, name="%s the Hallowed"},
{id=111, name="Loremaster %s"},
{id=112, name="%s of the Alliance"},
{id=113, name="%s of the Horde"},
{id=120, name="%s the Magic Seeker"},
{id=121, name="Twilight Vanquisher %s"},
{id=122, name="%s, Conqueror of Naxxramas"},
{id=123, name="%s, Hero of the Frozen Wastes"},
{id=124, name="%s the Hallowed"},
{id=125, name="Loremaster %s"},
{id=126, name="%s of the Alliance"},
{id=127, name="%s of the Horde"},
{id=128, name="%s the Flawless Victor"},
{id=129, name="%s, Champion of the Frozen Wastes"},
{id=130, name="Ambassador %s"},
{id=131, name="%s the Argent Champion"},
{id=132, name="%s, Guardian of Cenarius"},
{id=133, name="Brewmaster %s"},
{id=134, name="Merrymaker %s"},
{id=135, name="%s the Love Fool"},
{id=136, name="%s the Love Fool"},
{id=137, name="Matron %s"},
{id=138, name="Patron %s"},
{id=139, name="Obsidian Slayer %s"},
{id=140, name="%s of the Nightfall"},
{id=141, name="%s the Immortal"},
{id=142, name="%s the Undying"},
{id=143, name="%s Jenkins"},
{id=144, name="Bloodsail Admiral %s"},
{id=145, name="%s the Insane"},
{id=146, name="%s of the Exodar"},
{id=147, name="%s of Darnassus"},
{id=148, name="%s of Ironforge"},
{id=149, name="%s of Stormwind"},
{id=150, name="%s of Orgrimmar"},
{id=151, name="%s of Sen'jin"},
{id=152, name="%s of Silvermoon"},
{id=153, name="%s of Thunder Bluff"},
{id=154, name="%s of the Undercity"},
{id=155, name="%s the Noble"},
{id=156, name="Crusader %s"},
{id=157, name="Deadly Gladiator %s"},
{id=158, name="%s, Death's Demise"},
{id=159, name="%s the Celestial Defender"},
{id=160, name="%s, Conqueror of Ulduar"},
{id=161, name="%s, Champion of Ulduar"},
{id=162, name="%s the Astral Walker"},
{id=163, name="Vanquisher %s"},
{id=164, name="Starcaller %s"},
{id=165, name="%s the Astral Walker"},
{id=166, name="%s, Herald of the Titans"},
{id=167, name="Furious Gladiator %s"},
{id=168, name="%s the Pilgrim"},
{id=169, name="Relentless Gladiator %s"},
{id=170, name="Grand Crusader %s"},
{id=171, name="%s the Argent Defender"},
{id=172, name="%s the Patient"},
{id=173, name="%s the Light of Dawn"},
{id=174, name="%s, Bane of the Fallen King"},
{id=175, name="%s the Kingslayer"},
{id=176, name="%s of the Ashen Verdict"},
{id=177, name="Wrathful Gladiator %s"},
}
