-- Transmorpher title list — 3.3.5a (build 12340) CharTitles.dbc.
--
-- `id` is the CharTitles.dbc **Mask_ID** (the "InGameOrder" / bit index), NOT the
-- CharTitles row id. This is the value the client stores in PLAYER_FIELD_CHOSEN_TITLE
-- and the bit index it uses in the PLAYER_FIELD_KNOWN_TITLES bitmask (RE-confirmed in
-- StealthMorpher: Morpher.cpp writes titleId straight to CHOSEN_TITLE; Utils.cpp
-- IsTitleKnown/SetTitleKnown index the bitmask by titleId/32 : titleId%32). The engine
-- then displays the CharTitles row whose Mask_ID == CHOSEN_TITLE.
--
-- The OLD table used CharTitles ROW ids as `id`. Row id == Mask_ID only for the low PvP
-- ranks (1-28), so those happened to work, but every later title was off: e.g. "Crusader"
-- (row 156, Mask_ID 123) was stored as id=96, and Mask_ID 96 is "the Flawless Victor" — the
-- exact symptom reported. Source: cmangos CharTitles.dbc dump (3.3.5), anchored against the
-- live client (Mask_ID 96 = Flawless Victor). Ordered by Mask_ID; no duplicates.
Transmorpher_Titles = {
{id=1,   name="Private %s"},
{id=2,   name="Corporal %s"},
{id=3,   name="Sergeant %s"},
{id=4,   name="Master Sergeant %s"},
{id=5,   name="Sergeant Major %s"},
{id=6,   name="Knight %s"},
{id=7,   name="Knight-Lieutenant %s"},
{id=8,   name="Knight-Captain %s"},
{id=9,   name="Knight-Champion %s"},
{id=10,  name="Lieutenant Commander %s"},
{id=11,  name="Commander %s"},
{id=12,  name="Marshal %s"},
{id=13,  name="Field Marshal %s"},
{id=14,  name="Grand Marshal %s"},
{id=15,  name="Scout %s"},
{id=16,  name="Grunt %s"},
{id=17,  name="Sergeant %s"},
{id=18,  name="Senior Sergeant %s"},
{id=19,  name="First Sergeant %s"},
{id=20,  name="Stone Guard %s"},
{id=21,  name="Blood Guard %s"},
{id=22,  name="Legionnaire %s"},
{id=23,  name="Centurion %s"},
{id=24,  name="Champion %s"},
{id=25,  name="Lieutenant General %s"},
{id=26,  name="General %s"},
{id=27,  name="Warlord %s"},
{id=28,  name="High Warlord %s"},
{id=29,  name="Gladiator %s"},
{id=30,  name="Duelist %s"},
{id=31,  name="Rival %s"},
{id=32,  name="Challenger %s"},
{id=33,  name="Scarab Lord %s"},
{id=34,  name="Conqueror %s"},
{id=35,  name="Justicar %s"},
{id=36,  name="%s, Champion of the Naaru"},
{id=37,  name="Merciless Gladiator %s"},
{id=38,  name="%s of the Shattered Sun"},
{id=39,  name="%s, Hand of A'dal"},
{id=40,  name="Vengeful Gladiator %s"},
{id=41,  name="Battlemaster %s"},
{id=42,  name="%s the Seeker"},
{id=43,  name="Elder %s"},
{id=44,  name="Flame Warden %s"},
{id=45,  name="Flame Keeper %s"},
{id=46,  name="%s the Exalted"},
{id=47,  name="%s the Explorer"},
{id=48,  name="%s the Diplomat"},
{id=49,  name="Brutal Gladiator %s"},
{id=50,  name="Arena Master %s"},
{id=51,  name="Salty %s"},
{id=52,  name="Chef %s"},
{id=53,  name="%s the Supreme"},
{id=54,  name="%s of the Ten Storms"},
{id=55,  name="%s of the Emerald Dream"},
{id=56,  name="Deadly Gladiator %s"},
{id=57,  name="Prophet %s"},
{id=58,  name="%s the Malefic"},
{id=59,  name="Stalker %s"},
{id=60,  name="%s of the Ebon Blade"},
{id=61,  name="Archmage %s"},
{id=62,  name="Warbringer %s"},
{id=63,  name="Assassin %s"},
{id=64,  name="Grand Master Alchemist %s"},
{id=65,  name="Grand Master Blacksmith %s"},
{id=66,  name="Iron Chef %s"},
{id=67,  name="Grand Master Enchanter %s"},
{id=68,  name="Grand Master Engineer %s"},
{id=69,  name="Doctor %s"},
{id=70,  name="Grand Master Angler %s"},
{id=71,  name="Grand Master Herbalist %s"},
{id=72,  name="Grand Master Scribe %s"},
{id=73,  name="Grand Master Jewelcrafter %s"},
{id=74,  name="Grand Master Leatherworker %s"},
{id=75,  name="Grand Master Miner %s"},
{id=76,  name="Grand Master Skinner %s"},
{id=77,  name="Grand Master Tailor %s"},
{id=78,  name="%s of Quel'Thalas"},
{id=79,  name="%s of Argus"},
{id=80,  name="%s of Khaz Modan"},
{id=81,  name="%s of Gnomeregan"},
{id=82,  name="%s the Lion Hearted"},
{id=83,  name="%s, Champion of Elune"},
{id=84,  name="%s, Hero of Orgrimmar"},
{id=85,  name="Plainsrunner %s"},
{id=86,  name="%s of the Darkspear"},
{id=87,  name="%s the Forsaken"},
{id=88,  name="%s the Magic Seeker"},
{id=89,  name="Twilight Vanquisher %s"},
{id=90,  name="%s, Conqueror of Naxxramas"},
{id=91,  name="%s, Hero of Northrend"},
{id=92,  name="%s the Hallowed"},
{id=93,  name="Loremaster %s"},
{id=94,  name="%s of the Alliance"},
{id=95,  name="%s of the Horde"},
{id=96,  name="%s the Flawless Victor"},
{id=97,  name="%s, Champion of the Frozen Wastes"},
{id=98,  name="Ambassador %s"},
{id=99,  name="%s the Argent Champion"},
{id=100, name="%s, Guardian of Cenarius"},
{id=101, name="Brewmaster %s"},
{id=102, name="Merrymaker %s"},
{id=103, name="%s the Love Fool"},
{id=104, name="Matron %s"},
{id=105, name="Patron %s"},
{id=106, name="Obsidian Slayer %s"},
{id=107, name="%s of the Nightfall"},
{id=108, name="%s the Immortal"},
{id=109, name="%s the Undying"},
{id=110, name="%s Jenkins"},
{id=111, name="Bloodsail Admiral %s"},
{id=112, name="%s the Insane"},
{id=113, name="%s of the Exodar"},
{id=114, name="%s of Darnassus"},
{id=115, name="%s of Ironforge"},
{id=116, name="%s of Stormwind"},
{id=117, name="%s of Orgrimmar"},
{id=118, name="%s of Sen'jin"},
{id=119, name="%s of Silvermoon"},
{id=120, name="%s of Thunder Bluff"},
{id=121, name="%s of the Undercity"},
{id=122, name="%s the Noble"},
{id=123, name="Crusader %s"},
{id=124, name="%s, Death's Demise"},
{id=125, name="%s the Celestial Defender"},
{id=126, name="%s, Conqueror of Ulduar"},
{id=127, name="%s, Champion of Ulduar"},
{id=128, name="Vanquisher %s"},
{id=129, name="Starcaller %s"},
{id=130, name="%s the Astral Walker"},
{id=131, name="%s, Herald of the Titans"},
{id=132, name="Furious Gladiator %s"},
{id=133, name="%s the Pilgrim"},
{id=134, name="Relentless Gladiator %s"},
{id=135, name="Grand Crusader %s"},
{id=136, name="%s the Argent Defender"},
{id=137, name="%s the Patient"},
{id=138, name="%s the Light of Dawn"},
{id=139, name="%s, Bane of the Fallen King"},
{id=140, name="%s the Kingslayer"},
{id=141, name="%s of the Ashen Verdict"},
{id=142, name="Wrathful Gladiator %s"},
}
